### ISSUE TITLE
Header text font fit

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#16]
Now: District of Columbia Energy Benchmarking 

Change to (make smaller) : 
District of Columbia 
Energy Benchmarking

**Comment by emilyhobson** [comment]
Need to scale when new logos are in place

**Comment by emilyhobson** [comment]
The header image should be 95 pixels heigh, and no more 500 pixels wide. This will allow the site to look good even on screens with only 1024 pixels of horizontal space. The text should be offset 30 pixels from the left.
 
*  mobile-optimized 
* right offset-- 30 pixel right offset, it would be 530px wide 
* transparent GIF or PNG s

**Comment by emilyhobson** [comment]
@alecburch Confirm these are in the right format (transparent), then reassign to Greg?

**Comment by alecburch** [comment]
So is this logo replacing the two previous ones (DOEE and Sustainable DC)? @emilyhobson?

**Comment by emilyhobson** [comment]
No.  DC text,  energy logo,  sustainable,  skyline should all be included.  Greg needs the transparent png combo files.

**Comment by alecburch** [comment]
covering this in #2
