### ISSUE TITLE
DNS pointer

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#22]
Point to their domain

**Comment by emilyhobson** [comment]
energybenchmarkingdc.org (http://en.gandi.net/whois/details/?search=energybenchmarkingdc.org)
energybenchmarkingdc.com (http://en.gandi.net/whois/details/?search=energybenchmarkingdc.com)

The .com one is just set up to forward to the .org (I registered it because people often just assume .com). It’s the energybenchmarkingdc.org that I was to link to github.

Please add the energybenchmarkingdc.org as the custom domain on github asap. github says we need to do that before the dns can be updated to point to it. Please make sure you’re doing it for the /dc sub-section… Thanks!

**Comment by sconnelley** [comment]
`energybenchmarkingdc.org` has been added.

**Comment by sconnelley** [comment]
Everything points to `energybenchmarkingdc.org` now.
