### ISSUE TITLE
Property type categories

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#29]
Marshall is going to clean up the grouping of category types and supply to us on 9/9

**Comment by sconnelley** [comment]
** NEW **
![image](https://cloud.githubusercontent.com/assets/565486/18979115/22dbd3ba-8696-11e6-9a96-3c1a488c4f92.png)

** PREVIOUS **
![image](https://cloud.githubusercontent.com/assets/565486/18979154/71a01510-8696-11e6-8c9c-e4a9139ba705.png)
