### ISSUE TITLE
missing data - electricity and  natural gas use - 2015 and 2014

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#30]
The EUI shouldn't go above 1000 but it looks like that cleanup was applied to all the fields
Marshall is going to clean up the 2015 data (re-send data on Friday)

**Comment by sconnelley** [comment]
@emilyhobson here is what those filters look like following the new data update

**2015**
![image](https://cloud.githubusercontent.com/assets/565486/18978332/4221be34-8690-11e6-96a0-a4e0c186578a.png)
