### ISSUE TITLE
Missing property type info - 2013

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#31]
Data file: https://docs.google.com/spreadsheets/d/1XfoR-K7yTgGaRoMUi4R5qSjA5WLfv8j4AVd-Q8U8xww/edit#gid=412661165

![image](https://cloud.githubusercontent.com/assets/824082/18293878/58e62158-744a-11e6-816a-87a0866d19e0.png)

**Comment by emilyhobson** [comment]
Looks like this year has only one Property Type instead of the two in the other years:
Primary Property Type - Self Selected	Primary Property Type - EPA Calculated

Asking Marshall

**Comment by sconnelley** [comment]
New data has been uploaded and appears to have fixed the issue
![image](https://cloud.githubusercontent.com/assets/565486/18978245/71fde840-868f-11e6-9794-8a36867ba84f.png)
