### ISSUE TITLE
Domain name 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#32]
-Our PIO has decided we want the site to have the URL www.energybenchmarkingdc.org. As I have previously mentioned, we need to not have the visible url be cityenergyproject.github, because “City Energy Project” is a term for a group of cities whose work is funded through a grant to IMT and NRDC, and we’re not part of that group. Can Stamen register this URL and link it to the site?

**Comment by sconnelley** [comment]
Done.
