### ISSUE TITLE
Logo swap and Link

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#33]
- [x] Please change the top-left image to use the attached revised title that moves DC to after energy benchmarking, 
Logo file https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=rx0u3g99t6f3#attid%253Datt_15771bc7a14aa633_0.2

- [x] And link to http://doee.dc.gov/energybenchmarking/ from this logo and the Sustainable DC logos

**Comment by sconnelley** [comment]
@emilyhobson - that logo link doesn't work.  Can you paste/upload logo to a comment.

**Comment by sconnelley** [comment]
I think I found it, https://drive.google.com/drive/u/0/folders/0B5tBIGe_xerccU1vQzMwak1hMXc

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/18979887/dc2c820a-869c-11e6-9839-80069d4b2536.png)
