### ISSUE TITLE
Remove URL string in Energy Star description 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#35]
-In the “More info” on Energy Star Score, there is a link that is fully written out but can’t be clicked on, or even highlighted and copied.  Please remove this URL.  

![image](https://cloud.githubusercontent.com/assets/824082/18928987/6ac87112-8577-11e6-8430-d42b19051a5c.png)

In File: https://github.com/cityenergyproject/dc/blob/740edfbefdec7d8e37eae30e76205c2697edb72b/src/cities/dc.json

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/18979898/f0832d26-869c-11e6-9b44-5864f85bb7f8.png)
