### ISSUE TITLE
Link to DC site and to download data

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#36]
Provide two links to the DC sites:

- [ ]  “More about DOEE’s energy and water benchmarking program”   http://doee.dc.gov/energybenchmarking/,  
- [ ] but the other is the ability to DOWNLOAD THE DATA (url http://doee.dc.gov/page/energy-benchmarking-disclosure) . By mutual agreement, we decided the best way to do this right now was to have a link to our own website, rather than trying to have it pull a spreadsheet dynamically from Cardo. I think the idea was this would be in the footer but (a) I don’t see it there, and (b) its not the most visible place anyway.

**Comment by emilyhobson** [comment]
Option A: 
![image](https://cloud.githubusercontent.com/assets/824082/18966225/51364a6c-8635-11e6-9003-8006a84b2e24.png)

Option B: (worse)
![image](https://cloud.githubusercontent.com/assets/824082/18966244/6074b4b4-8635-11e6-8378-77e83125cb4c.png)

Option C: Footer

**Comment by alecburch** [comment]
Footer using http://fiddle.jshell.net/764396ho/ would be helpful given the length of the page. 

![screen shot 2016-09-29 at 11 13 52 am](https://cloud.githubusercontent.com/assets/5263476/18966393/dea37fdc-8635-11e6-8687-c4e9b6d8b1a1.png)

**Comment by emilyhobson** [comment]
Feasibility on the footer, @sconnelley , when you can.

**Comment by sconnelley** [comment]
Wouldn't be hard to test the fiddle out, but personally Option A seems reasonable sufficient

**Comment by emilyhobson** [comment]
Kk

**Comment by emilyhobson** [comment]
Option A approved but About link/text should be first. 

About link: http://doee.dc.gov/page/about-benchmarking
Download link: http://doee.dc.gov/node/572252

**Comment by sconnelley** [comment]
Ah man, just finished Option C

**Comment by emilyhobson** [comment]
Well then, let's push forward with C ! The links should reflect the new ones, though.
