### ISSUE TITLE
improve mobile responsiveness

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#44]
Mobile and tablet responsive improvements: Minimal improvements to the interactivity of the responsive version of the site. Mobile "failover" message will still lead on these devices. 

Improvements to the functionality of the metrics pane on mobile devices and ability to select buildings

**Comment by emilyhobson** [comment]
Revisit post release (to DOEE) of #42

**Comment by sconnelley** [comment]
this is covered in #42
