### ISSUE TITLE
color ramps 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#46]
Color ramps: Adopt improved color scheme for the building dots that shows gradations better, near to or as specifically implemented for the City of Seattle’s version of the Energy Benchmarking Platform open source code base.

**Comment by nicolettehayes** [comment]
![dc-0531-buildingdetail](https://user-images.githubusercontent.com/12550451/27559318-fc2fa15c-5a74-11e7-8e8c-59fdb3807f98.jpg)
