### ISSUE TITLE
two freestanding pages

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#47]
Create two freestanding pages and a links from the main site : 

- [x] Help document (FAQ) 
- [x] Glossary (DOEE will provide content)

**Comment by nicolettehayes** [comment]
![cep-wdc-0613-faq](https://user-images.githubusercontent.com/12550451/27559259-c7d4aa56-5a74-11e7-9139-92ef47469a88.jpg)
![cep-wdc-0613-glossary](https://user-images.githubusercontent.com/12550451/27559261-c9894e38-5a74-11e7-99e6-b632516a1c7b.jpg)

**Comment by sconnelley** [comment]
see the #42 for how the footer should be

**Comment by nicolettehayes** [comment]
Can't imagine this being _super_ useful, but here it is just in case!

https://drive.google.com/a/stamen.com/file/d/0B36c8E17SDHGSVBJcGRlTFhDYUU/view?usp=sharing

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/27880644-ae5e871a-6193-11e7-95a7-260246dd3222.png)

![image](https://user-images.githubusercontent.com/565486/27880659-b71d8aa4-6193-11e7-99d8-6f41c2af30ef.png)

**Comment by sconnelley** [comment]
These are fundamentally done.  Start new issues for specific changes
