### ISSUE TITLE
Include "Beta" label

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#49]
Ask DC for location

**Comment by emilyhobson** [comment]
to @nicolettehayes for location

**Comment by nicolettehayes** [comment]
![cep-wdc-logo](https://cloud.githubusercontent.com/assets/12550451/26656258/2d28f982-4613-11e7-830a-a0daca46ecb3.png)

https://drive.google.com/a/stamen.com/file/d/0B36c8E17SDHGWE13ZVRzNW1PeU0/view?usp=sharing

![screen shot 2017-05-31 at 3 07 28 pm](https://cloud.githubusercontent.com/assets/12550451/26656180/e7771c3e-4612-11e7-853e-126e0277fd94.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/27697938-ad5c88b4-5cc3-11e7-9b6f-e642120944fd.png)

**Comment by nicolettehayes** [comment]
@sconnelley I uploaded the double resolution version to the drive:

https://drive.google.com/open?id=0B36c8E17SDHGbFQzZ295V2FaYWs

![cep-wdc-logo](https://user-images.githubusercontent.com/12550451/27756762-891588e2-5daf-11e7-8317-f69550d39ce6.png)
<img width="536" alt="cep-wdc-logo 2x" src="https://user-images.githubusercontent.com/12550451/27756763-8919f332-5daf-11e7-9f1c-4f42438901ad.png">
