### ISSUE TITLE
mobile failover or warning 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#50]
Mobile messaging: Provide “failover” state for mobile users communicating optimum viewing conditions may be on a larger desktop screen and browser.

**Comment by nicolettehayes** [comment]
![cep-wdc-0613-mobilefailover](https://user-images.githubusercontent.com/12550451/27559304-ed751f48-5a74-11e7-83d1-92098b581334.jpg)

**Comment by emilyhobson** [comment]
Text change  - “For best results, please view this site on a larger screen.”

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28833539-9a2885d2-76ad-11e7-8a3d-263d6a39d020.png)
