### ISSUE TITLE
collapse option

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#51]
Add clearer "collapse" option to the drop-down filter menus (metric filters)

**Comment by nicolettehayes** [comment]
same type size as the "more info" beneath it, right-aligned with the arrow in "more info", says collapse when open, expand when closed.

![screen shot 2017-05-31 at 3 12 40 pm](https://cloud.githubusercontent.com/assets/12550451/26656372/9ee70c12-4613-11e7-81d4-f4fd81049cfc.png)

Also, the dropdown should close when you click away.

![screen shot 2017-05-31 at 3 13 53 pm](https://cloud.githubusercontent.com/assets/12550451/26656404/ca3e56a4-4613-11e7-8744-e1a2b3fe2c78.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/27800622-3065ae8a-5fe8-11e7-8b46-d609179fd841.png)

**Comment by sconnelley** [comment]
Expand text added
![image](https://user-images.githubusercontent.com/565486/28038307-797efb68-658c-11e7-94ce-90b1dc722ec3.png)
