### ISSUE TITLE
Reset filters link

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#52]
Add "Reset Filters" link to clear all metric filters

**Comment by nicolettehayes** [comment]
Add a "reset all" button that will both clear the filters from the metrics on the left AND reset the dropdown map controls to show all.

![screen shot 2017-05-31 at 3 24 10 pm](https://cloud.githubusercontent.com/assets/12550451/26656744/38701a44-4615-11e7-9931-3b52cd4910af.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/27803847-98edef88-5ff9-11e7-8827-6209a9a3b4bb.png)
