### ISSUE TITLE
More clear collapse on checkbox dropdows

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#55]
This part of the SOW states that we would like to make it more apparent how to collapse the drop-down menus. I believe we discussed this in our kick-off meeting, but looking at the map now, I think there must have been a bit of a misunderstanding. What we meant for this task was to create a “Collapse” option for the drop-down menus that appear at the top of the screen – for Ward, Property Type, and Report Status; it seems to me that the collapse option was actually applied to the Metric Filters on the left-hand side of the screen.

![image](https://user-images.githubusercontent.com/824082/28032855-e542fc4a-6560-11e7-8a09-e13176e1b570.png)

Perhaps an X in the button area when the drop down is present?

**Comment by sconnelley** [comment]
@emilyhobson -- issue #51 is the only "collapse" issue

**Comment by sconnelley** [comment]
We could use down & up triangles, shouldn't take too long

**Comment by sconnelley** [comment]
Added arrows for now:
**closed**
![image](https://user-images.githubusercontent.com/565486/28037891-fd8f3c4e-658a-11e7-8bdd-80ee468316ec.png)

**open**
![image](https://user-images.githubusercontent.com/565486/28037911-0bf89b04-658b-11e7-94a9-a77554a9c29c.png)
