### ISSUE TITLE
Water use low end

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/dc#58]
It looks like there's a default of "1" of the low end of water use but in reality it's around 18,000. Since the range is so high for this metric, it's  causing the histogram to be even flatter than it needs to be.

![image](https://user-images.githubusercontent.com/824082/29296888-f1d6a908-8111-11e7-8be4-07f2a11a2fc2.png)

**Comment by sconnelley** [comment]
Actually setting the max range value to 18,000 seemed to work pretty good.
![image](https://user-images.githubusercontent.com/565486/29580452-eb00fb46-872a-11e7-9da3-657efb2b9d39.png)
